height: 826
skeleton:
- loc:
  - 377
  - 476
  name: root
  parent: null
- loc:
  - 377
  - 476
  name: hip
  parent: root
- loc:
  - 377
  - 240
  name: torso
  parent: hip
- loc:
  - 382
  - 122
  name: neck
  parent: torso
- loc:
  - 303
  - 240
  name: right_shoulder
  parent: torso
- loc:
  - 185
  - 250
  name: right_elbow
  parent: right_shoulder
- loc:
  - 58
  - 260
  name: right_hand
  parent: right_elbow
- loc:
  - 451
  - 240
  name: left_shoulder
  parent: torso
- loc:
  - 569
  - 250
  name: left_elbow
  parent: left_shoulder
- loc:
  - 696
  - 250
  name: left_hand
  parent: left_elbow
- loc:
  - 333
  - 476
  name: right_hip
  parent: root
- loc:
  - 323
  - 634
  name: right_knee
  parent: right_hip
- loc:
  - 313
  - 781
  name: right_foot
  parent: right_knee
- loc:
  - 421
  - 476
  name: left_hip
  parent: root
- loc:
  - 441
  - 634
  name: left_knee
  parent: left_hip
- loc:
  - 451
  - 781
  name: left_foot
  parent: left_knee
width: 755
