height: 821
skeleton:
- loc:
  - 325
  - 471
  name: root
  parent: null
- loc:
  - 325
  - 471
  name: hip
  parent: root
- loc:
  - 330
  - 240
  name: torso
  parent: hip
- loc:
  - 330
  - 127
  name: neck
  parent: torso
- loc:
  - 260
  - 240
  name: right_shoulder
  parent: torso
- loc:
  - 155
  - 249
  name: right_elbow
  parent: right_shoulder
- loc:
  - 51
  - 249
  name: right_hand
  parent: right_elbow
- loc:
  - 399
  - 240
  name: left_shoulder
  parent: torso
- loc:
  - 504
  - 240
  name: left_elbow
  parent: left_shoulder
- loc:
  - 617
  - 240
  name: left_hand
  parent: left_elbow
- loc:
  - 277
  - 475
  name: right_hip
  parent: root
- loc:
  - 260
  - 632
  name: right_knee
  parent: right_hip
- loc:
  - 234
  - 780
  name: right_foot
  parent: right_knee
- loc:
  - 373
  - 467
  name: left_hip
  parent: root
- loc:
  - 408
  - 623
  name: left_knee
  parent: left_hip
- loc:
  - 452
  - 763
  name: left_foot
  parent: left_knee
width: 669
