height: 235
skeleton:
- loc:
  - 109
  - 127
  name: root
  parent: null
- loc:
  - 109
  - 127
  name: hip
  parent: root
- loc:
  - 112
  - 75
  name: torso
  parent: hip
- loc:
  - 110
  - 60
  name: neck
  parent: torso
- loc:
  - 60
  - 78
  name: right_shoulder
  parent: torso
- loc:
  - 43
  - 101
  name: right_elbow
  parent: right_shoulder
- loc:
  - 28
  - 130
  name: right_hand
  parent: right_elbow
- loc:
  - 163
  - 72
  name: left_shoulder
  parent: torso
- loc:
  - 177
  - 92
  name: left_elbow
  parent: left_shoulder
- loc:
  - 192
  - 118
  name: left_hand
  parent: left_elbow
- loc:
  - 90
  - 127
  name: right_hip
  parent: root
- loc:
  - 87
  - 171
  name: right_knee
  parent: right_hip
- loc:
  - 84
  - 215
  name: right_foot
  parent: right_knee
- loc:
  - 128
  - 127
  name: left_hip
  parent: root
- loc:
  - 125
  - 171
  name: left_knee
  parent: left_hip
- loc:
  - 122
  - 215
  name: left_foot
  parent: left_knee
width: 224
